
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdphy.h"

/*
* The configuration table for devices
*/

XDphy_Config XDphy_ConfigTable[XPAR_XDPHY_NUM_INSTANCES] =
{
	{
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_DEVICE_ID,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_BASEADDR,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_DPHY_MODE,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_EN_REG_IF,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_DPHY_LANES,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_ESC_CLK_PERIOD,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_ESC_TIMEOUT,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_HS_LINE_RATE,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_HS_TIMEOUT,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_LPX_PERIOD,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_STABLE_CLK_PERIOD,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_TXPLL_CLKIN_PERIOD,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_WAKEUP,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_EN_TIMEOUT_REGS,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_HS_SETTLE_NS
	}
};


