#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : zynq_imgproc_bd.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Apr 18 13:39:24 +0800 2026
# SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: zynq_imgproc_bd.sh [-help]
# usage: zynq_imgproc_bd.sh [-lib_map_path]
# usage: zynq_imgproc_bd.sh [-noclean_files]
# usage: zynq_imgproc_bd.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'zynq_imgproc_bd.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip axi_infrastructure_v1_1_0 axi_vip_v1_1_7 zynq_ultra_ps_e_vip_v1_0_7 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_21 fifo_generator_v13_2_5 axi_data_fifo_v2_1_20 axi_crossbar_v2_1_22 mipi_csi2_rx_ctrl_v1_0_8 high_speed_selectio_wiz_v3_6_0 mipi_dphy_v4_2_0 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_21 axis_dwidth_converter_v1_1_20 vfb_v1_0_15 lib_pkg_v1_0_2 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_iic_v2_0_24 axi_gpio_v2_0_23 xlconstant_v1_1_7 smartconnect_v1_0 lib_fifo_v1_0_14 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_23 axi_sg_v4_1_13 axi_dma_v7_1_22 xlslice_v1_0_2)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "zynq_imgproc_bd.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ce6c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_zynq_ultra_ps_e_0_0/sim/zynq_imgproc_bd_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_rst_ps8_0_150m_0/sim/zynq_imgproc_bd_rst_ps8_0_150m_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2ef9/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/47c9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b68e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_0/sim/bd_bf7d_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_1/sim/bd_bf7d_r_sync_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work mipi_csi2_rx_ctrl_v1_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl/mipi_csi2_rx_ctrl_v1_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_2/sim/bd_bf7d_rx_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work high_speed_selectio_wiz_v3_6_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/bc56/hdl/high_speed_selectio_wiz_v3_6_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/ip_0/hdl/bd_bf7d_phy_0_hssio_rx_mipi_iobuf_rx.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/ip_0/bd_bf7d_phy_0_hssio_rx_hssio_wiz_top.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/ip_0/bd_bf7d_phy_0_hssio_rx_high_speed_selectio_wiz_v3_6_0.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/ip_0/sim/bd_bf7d_phy_0_hssio_rx.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work mipi_dphy_v4_2_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/3f2e/hdl/mipi_dphy_v4_2_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf7d_phy_0/support/bd_bf7d_phy_0_support.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf7d_phy_0/support/bd_bf7d_phy_0_clock_module.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf7d_phy_0_c1.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf7d_phy_0_core.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf7d_phy_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/7da1/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_dwidth_converter_v1_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/5aec/hdl/axis_dwidth_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_4/ip_0/sim/bd_bf7d_vfb_0_0_axis_converter.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_4/bd_bf7d_vfb_0_0/src/verilog/bd_bf7d_vfb_0_0_fifo.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_4/bd_bf7d_vfb_0_0/src/verilog/bd_bf7d_vfb_0_0_fifo_sb.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_4/bd_bf7d_vfb_0_0/src/verilog/bd_bf7d_vfb_0_0_axis_dconverter.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work vfb_v1_0_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/381a/hdl/vfb_v1_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_4/bd_bf7d_vfb_0_0_core.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_4/bd_bf7d_vfb_0_0.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/sim/bd_bf7d.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/sim/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/d1e4/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_iic_0_0/sim/zynq_imgproc_bd_axi_iic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_23 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/bb35/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_gpio_0_0/sim/zynq_imgproc_bd_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_0/sim/bd_95fd_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_1/sim/bd_95fd_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_2/sim/bd_95fd_arinsw_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_3/sim/bd_95fd_rinsw_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_4/sim/bd_95fd_awinsw_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_5/sim/bd_95fd_winsw_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_6/sim/bd_95fd_binsw_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_7/sim/bd_95fd_aroutsw_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_8/sim/bd_95fd_routsw_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_9/sim/bd_95fd_awoutsw_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_10/sim/bd_95fd_woutsw_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_11/sim/bd_95fd_boutsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_12/sim/bd_95fd_arni_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_13/sim/bd_95fd_rni_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_14/sim/bd_95fd_awni_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_15/sim/bd_95fd_wni_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_16/sim/bd_95fd_bni_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/053f/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_17/sim/bd_95fd_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_18/sim/bd_95fd_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/9d43/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_19/sim/bd_95fd_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_20/sim/bd_95fd_s00a2s_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_21/sim/bd_95fd_sarn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_22/sim/bd_95fd_srn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_23/sim/bd_95fd_sawn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_24/sim/bd_95fd_swn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_25/sim/bd_95fd_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_26/sim/bd_95fd_m00s2a_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_27/sim/bd_95fd_m00arn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_28/sim/bd_95fd_m00rn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_29/sim/bd_95fd_m00awn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_30/sim/bd_95fd_m00wn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_31/sim/bd_95fd_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/7af8/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_32/sim/bd_95fd_m00e_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_33/sim/bd_95fd_m01s2a_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_34/sim/bd_95fd_m01arn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_35/sim/bd_95fd_m01rn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_36/sim/bd_95fd_m01awn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_37/sim/bd_95fd_m01wn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_38/sim/bd_95fd_m01bn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_39/sim/bd_95fd_m01e_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_40/sim/bd_95fd_m02s2a_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_41/sim/bd_95fd_m02arn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_42/sim/bd_95fd_m02rn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_43/sim/bd_95fd_m02awn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_44/sim/bd_95fd_m02wn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_45/sim/bd_95fd_m02bn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_46/sim/bd_95fd_m02e_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_47/sim/bd_95fd_m03s2a_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_48/sim/bd_95fd_m03arn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_49/sim/bd_95fd_m03rn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_50/sim/bd_95fd_m03awn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_51/sim/bd_95fd_m03wn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_52/sim/bd_95fd_m03bn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_53/sim/bd_95fd_m03e_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_54/sim/bd_95fd_m04s2a_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_55/sim/bd_95fd_m04arn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_56/sim/bd_95fd_m04rn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_57/sim/bd_95fd_m04awn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_58/sim/bd_95fd_m04wn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_59/sim/bd_95fd_m04bn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_60/sim/bd_95fd_m04e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/sim/bd_95fd.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/sim/zynq_imgproc_bd_axi_sc_cfg_0.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_0/sim/bd_cced_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_1/sim/bd_cced_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_2/sim/bd_cced_s00mmu_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_3/sim/bd_cced_s00tr_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_4/sim/bd_cced_s00sic_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_5/sim/bd_cced_s00a2s_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_6/sim/bd_cced_sawn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_7/sim/bd_cced_swn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_8/sim/bd_cced_sbn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_9/sim/bd_cced_m00s2a_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_10/sim/bd_cced_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/sim/bd_cced.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/sim/zynq_imgproc_bd_axi_sc_hp0_0.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_0/sim/bd_0cbc_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_1/sim/bd_0cbc_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_2/sim/bd_0cbc_s00mmu_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_3/sim/bd_0cbc_s00tr_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_4/sim/bd_0cbc_s00sic_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_5/sim/bd_0cbc_s00a2s_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_6/sim/bd_0cbc_sarn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_7/sim/bd_0cbc_srn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_8/sim/bd_0cbc_sawn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_9/sim/bd_0cbc_swn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_10/sim/bd_0cbc_sbn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_11/sim/bd_0cbc_m00s2a_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_12/sim/bd_0cbc_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/sim/bd_0cbc.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/sim/zynq_imgproc_bd_axi_sc_hp1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_23 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/af86/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_13 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_22 $vhdlan_opts \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/0fb1/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_dma_eth_0/sim/zynq_imgproc_bd_axi_dma_eth_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_0/sim/bd_0c4c_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_1/sim/bd_0c4c_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_2/sim/bd_0c4c_s00mmu_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_3/sim/bd_0c4c_s00tr_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_4/sim/bd_0c4c_s00sic_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_5/sim/bd_0c4c_s00a2s_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_6/sim/bd_0c4c_sawn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_7/sim/bd_0c4c_swn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_8/sim/bd_0c4c_sbn_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_9/sim/bd_0c4c_m00s2a_0.sv" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_10/sim/bd_0c4c_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/sim/bd_0c4c.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/sim/zynq_imgproc_bd_axi_sc_hp2_0.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_0_0/zynq_imgproc_bd_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_0_0/zynq_imgproc_bd_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_mipi_ref_0/zynq_imgproc_bd_clk_wiz_mipi_ref_0_clk_wiz.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_mipi_ref_0/zynq_imgproc_bd_clk_wiz_mipi_ref_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_rst_pclk_0_0/sim/zynq_imgproc_bd_rst_pclk_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ipshared/8b3d" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_xlslice_rst_0/sim/zynq_imgproc_bd_xlslice_rst_0.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_xlslice_pwdn_0/sim/zynq_imgproc_bd_xlslice_pwdn_0.v" \
    "$ref_dir/../../../bd/zynq_imgproc_bd/sim/zynq_imgproc_bd.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.zynq_imgproc_bd xil_defaultlib.glbl -o zynq_imgproc_bd_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./zynq_imgproc_bd_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./zynq_imgproc_bd.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key zynq_imgproc_bd_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc zynq_imgproc_bd_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./zynq_imgproc_bd.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: zynq_imgproc_bd.sh [-help]\n\
Usage: zynq_imgproc_bd.sh [-lib_map_path]\n\
Usage: zynq_imgproc_bd.sh [-reset_run]\n\
Usage: zynq_imgproc_bd.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
