# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/imgproc_axu4evb_ov5640.xdc

# Block Designs: bd/zynq_imgproc_bd/zynq_imgproc_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd || ORIG_REF_NAME==zynq_imgproc_bd} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_zynq_ultra_ps_e_0_0/zynq_imgproc_bd_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zynq_imgproc_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_rst_ps8_0_150m_0/zynq_imgproc_bd_rst_ps8_0_150m_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_rst_ps8_0_150m_0 || ORIG_REF_NAME==zynq_imgproc_bd_rst_ps8_0_150m_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0 || ORIG_REF_NAME==zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_iic_0_0/zynq_imgproc_bd_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_axi_iic_0_0 || ORIG_REF_NAME==zynq_imgproc_bd_axi_iic_0_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_gpio_0_0/zynq_imgproc_bd_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_axi_gpio_0_0 || ORIG_REF_NAME==zynq_imgproc_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/zynq_imgproc_bd_axi_sc_cfg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_axi_sc_cfg_0 || ORIG_REF_NAME==zynq_imgproc_bd_axi_sc_cfg_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/zynq_imgproc_bd_axi_sc_hp0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_axi_sc_hp0_0 || ORIG_REF_NAME==zynq_imgproc_bd_axi_sc_hp0_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/zynq_imgproc_bd_axi_sc_hp1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_axi_sc_hp1_0 || ORIG_REF_NAME==zynq_imgproc_bd_axi_sc_hp1_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_dma_eth_0/zynq_imgproc_bd_axi_dma_eth_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_axi_dma_eth_0 || ORIG_REF_NAME==zynq_imgproc_bd_axi_dma_eth_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/zynq_imgproc_bd_axi_sc_hp2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_axi_sc_hp2_0 || ORIG_REF_NAME==zynq_imgproc_bd_axi_sc_hp2_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_0_0/zynq_imgproc_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_clk_wiz_0_0 || ORIG_REF_NAME==zynq_imgproc_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_mipi_ref_0/zynq_imgproc_bd_clk_wiz_mipi_ref_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_clk_wiz_mipi_ref_0 || ORIG_REF_NAME==zynq_imgproc_bd_clk_wiz_mipi_ref_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_rst_pclk_0_0/zynq_imgproc_bd_rst_pclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_rst_pclk_0_0 || ORIG_REF_NAME==zynq_imgproc_bd_rst_pclk_0_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_xlslice_rst_0/zynq_imgproc_bd_xlslice_rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_xlslice_rst_0 || ORIG_REF_NAME==zynq_imgproc_bd_xlslice_rst_0} -quiet] -quiet

# IP: bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_xlslice_pwdn_0/zynq_imgproc_bd_xlslice_pwdn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_imgproc_bd_xlslice_pwdn_0 || ORIG_REF_NAME==zynq_imgproc_bd_xlslice_pwdn_0} -quiet] -quiet

# XDC: bd/zynq_imgproc_bd/zynq_imgproc_bd_ooc.xdc
