# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.runs/synth_1/imgproc_top_ov5640.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu4ev-sfvc784-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.cache/wt [current_project]
set_property parent.project_path D:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/common/axil_cfg_reg.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/project/src/bilateral_filter.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/project/src/clahe_engine.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/project/src/ddr3_pixel_buf.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/common/ram/fifo_async.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/common/ram/fifo_sync.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/project/src/frame_eth_tx.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/project/src/img_preprocessor.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/project/src/k_lut_rom.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/project/src/line_buffer_ctrl.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/project/src/local_detail_enhance_11x11.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/common/ram/ram_sdp_bram.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/common/ram/ram_sp_bram.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/common/ram/ram_tdp_bram.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/project/src/sensor_if.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/common/shift_reg.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/project/src/vga_timing_gen.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/project/src/zynq_display_ctrl.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/hdl/zynq_imgproc_bd_wrapper.v
  D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/sources_1/rtl_top/imgproc_top_ov5640.v
}
add_files D:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/zynq_imgproc_bd.bd
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_zynq_ultra_ps_e_0_0/zynq_imgproc_bd_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_zynq_ultra_ps_e_0_0/zynq_imgproc_bd_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_rst_ps8_0_150m_0/zynq_imgproc_bd_rst_ps8_0_150m_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_rst_ps8_0_150m_0/zynq_imgproc_bd_rst_ps8_0_150m_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_rst_ps8_0_150m_0/zynq_imgproc_bd_rst_ps8_0_150m_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_0/bd_bf7d_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_1/bd_bf7d_r_sync_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_1/bd_bf7d_r_sync_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_1/bd_bf7d_r_sync_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_2/bd_bf7d_rx_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_2/bd_bf7d_rx_0_fixed_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_2/bd_bf7d_rx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/ip_0/bd_bf7d_phy_0_hssio_rx.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/ip_0/bd_bf7d_phy_0_hssio_rx_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf7d_phy_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf7d_phy_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf7d_phy_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_4/bd_bf7d_vfb_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/bd_0/bd_bf7d_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0/zynq_imgproc_bd_mipi_csi2_rx_subsystem_0_0_fixed_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_iic_0_0/zynq_imgproc_bd_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_iic_0_0/zynq_imgproc_bd_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_gpio_0_0/zynq_imgproc_bd_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_gpio_0_0/zynq_imgproc_bd_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_gpio_0_0/zynq_imgproc_bd_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_1/bd_95fd_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_1/bd_95fd_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_2/bd_95fd_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_3/bd_95fd_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_4/bd_95fd_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_5/bd_95fd_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_6/bd_95fd_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_7/bd_95fd_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_8/bd_95fd_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_9/bd_95fd_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_10/bd_95fd_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_11/bd_95fd_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_12/bd_95fd_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_13/bd_95fd_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_14/bd_95fd_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_15/bd_95fd_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_16/bd_95fd_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_20/bd_95fd_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_21/bd_95fd_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_22/bd_95fd_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_23/bd_95fd_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_24/bd_95fd_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_25/bd_95fd_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_26/bd_95fd_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_27/bd_95fd_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_28/bd_95fd_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_29/bd_95fd_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_30/bd_95fd_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_31/bd_95fd_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_33/bd_95fd_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_34/bd_95fd_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_35/bd_95fd_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_36/bd_95fd_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_37/bd_95fd_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_38/bd_95fd_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_40/bd_95fd_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_41/bd_95fd_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_42/bd_95fd_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_43/bd_95fd_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_44/bd_95fd_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_45/bd_95fd_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_47/bd_95fd_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_48/bd_95fd_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_49/bd_95fd_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_50/bd_95fd_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_51/bd_95fd_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_52/bd_95fd_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_54/bd_95fd_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_55/bd_95fd_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_56/bd_95fd_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_57/bd_95fd_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_58/bd_95fd_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/bd_0/ip/ip_59/bd_95fd_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_cfg_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_1/bd_cced_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_1/bd_cced_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_5/bd_cced_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_6/bd_cced_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_7/bd_cced_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_8/bd_cced_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/bd_0/ip/ip_9/bd_cced_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_1/bd_0cbc_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_1/bd_0cbc_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_5/bd_0cbc_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_6/bd_0cbc_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_7/bd_0cbc_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_8/bd_0cbc_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_9/bd_0cbc_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_10/bd_0cbc_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/bd_0/ip/ip_11/bd_0cbc_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_dma_eth_0/zynq_imgproc_bd_axi_dma_eth_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_dma_eth_0/zynq_imgproc_bd_axi_dma_eth_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_dma_eth_0/zynq_imgproc_bd_axi_dma_eth_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_1/bd_0c4c_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_1/bd_0c4c_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_5/bd_0c4c_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_6/bd_0c4c_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_7/bd_0c4c_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_8/bd_0c4c_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/bd_0/ip/ip_9/bd_0c4c_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_axi_sc_hp2_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_0_0/zynq_imgproc_bd_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_0_0/zynq_imgproc_bd_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_0_0/zynq_imgproc_bd_clk_wiz_0_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_0_0/zynq_imgproc_bd_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_mipi_ref_0/zynq_imgproc_bd_clk_wiz_mipi_ref_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_mipi_ref_0/zynq_imgproc_bd_clk_wiz_mipi_ref_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_clk_wiz_mipi_ref_0/zynq_imgproc_bd_clk_wiz_mipi_ref_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_rst_pclk_0_0/zynq_imgproc_bd_rst_pclk_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_rst_pclk_0_0/zynq_imgproc_bd_rst_pclk_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/ip/zynq_imgproc_bd_rst_pclk_0_0/zynq_imgproc_bd_rst_pclk_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Project/Vivado/zynq4ev/imgproc_mpsoc/vivado_proj/imgproc_axu4evb_ov5640.srcs/sources_1/bd/zynq_imgproc_bd/zynq_imgproc_bd_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/imgproc_axu4evb_ov5640.xdc
set_property used_in_implementation false [get_files D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/imgproc_axu4evb_ov5640.xdc]
set_property processing_order LATE [get_files D:/Project/Vivado/zynq4ev/imgproc_mpsoc/files/imgproc_axu4evb_ov5640.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top imgproc_top_ov5640 -part xczu4ev-sfvc784-2-i
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef imgproc_top_ov5640.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file imgproc_top_ov5640_utilization_synth.rpt -pb imgproc_top_ov5640_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
